host_ip: 0.0.0.0
port: 3000
reload_on: true
update_time: 1
theme: gruv
tui_on: false
notifications_on: true
ntfy:
  url: null
  topic: portfolio
recaps:
  daily: true
  weekly: true
  monthly: true
ticker_movement_threshhold:
  low: 5
  medium: 15
  high: 30
  panic: 50
total_movement_threshhold:
  low: 5
  medium: 10
  high: 20
  panic: 40
